### ISSUE TITLE
Uri does not parse "+" correctly.

### ISSUE THREAD

**Issue by eric-poitras** [derek-watson/jsUri#47]
There is a change between version v1.1.1 and v1.3 that breaks compatibility.

In this example:
new Uri("http://localhost?myparam=toto+titi")

The "+" should be parsed as a space since in this form, the parameters are encoded but now it parses as an actual plus sign (%2B).

Expected behaviour (one of the two) :

new Uri("http://localhost?myparam=toto+titi").toString() === "http://localhost?myparam=toto%20titi" 
or
new Uri("http://localhost?myparam=toto+titi").toString() === "http://localhost?myparam=toto+titi" 

Current (wrong) behaviour:
new Uri("http://localhost?myparam=toto+titi").toString() === "http://localhost?myparam=toto%2Btiti"

The library has the correct behaviour in this case and this should not change:

new Uri( "http://localhost").replaceQueryParam("myparam", "toto+titi" ).toString() ===
"http://localhost/?myparam=toto%2Btiti"

Further information:

This "+" thing seems to be used by modern browser only when posting form as get (urlencoredform). It is however also used in the good old java api URLEncoder.

So users probably affected by this bugs are those interacting with java (URLEncoder) and Jersey's URIBuilder api and those using the library for decoding current page query parameters. (Ex: new Uri( window.location )  )

Even more information:

If you want to laugh (or cry): http://unixpapa.com/js/querystring.html

**Comment by eric-poitras** [comment]
If you want to laugh (or cry): http://unixpapa.com/js/querystring.html

**Comment by eric-poitras** [comment]
You can close the bug since you merged my fix.

**Comment by derek-watson** [comment]
Thank you!
